# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(800, 800))
        Form.setMaximumSize(QtCore.QSize(800, 800))
        self.pushButton2_1 = QtWidgets.QPushButton(Form)
        self.pushButton2_1.setGeometry(QtCore.QRect(20, 20, 101, 41))
        self.pushButton2_1.setStyleSheet("background-color: #007BFF; /* Цвет фона кнопки */\n"
"    color: white; /* Цвет текста */\n"
"    font-size: 16px; /* Размер шрифта */\n"
"    font-family: Arial, sans-serif; /* Шрифт */\n"
"    padding: 10px 20px; /* Отступы внутри кнопки */\n"
"    border: none; /* Без рамки */\n"
"    border-radius: 5px; /* Закругление углов */\n"
"    cursor: pointer; /* Указатель при наведении */")
        self.pushButton2_1.setObjectName("pushButton2_1")
        self.pushButton_save = QtWidgets.QPushButton(Form)
        self.pushButton_save.setGeometry(QtCore.QRect(660, 20, 121, 41))
        self.pushButton_save.setStyleSheet("background-color: #007BFF; /* Цвет фона кнопки */\n"
"    color: white; /* Цвет текста */\n"
"    font-size: 16px; /* Размер шрифта */\n"
"    font-family: Arial, sans-serif; /* Шрифт */\n"
"    padding: 10px 20px; /* Отступы внутри кнопки */\n"
"    border: none; /* Без рамки */\n"
"    border-radius: 5px; /* Закругление углов */\n"
"    cursor: pointer; /* Указатель при наведении */")
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_img = QtWidgets.QPushButton(Form)
        self.pushButton_img.setEnabled(True)
        self.pushButton_img.setGeometry(QtCore.QRect(260, 20, 281, 261))
        self.pushButton_img.setStyleSheet("background-color: #007BFF; /* Цвет фона кнопки */\n"
"    color: white; /* Цвет текста */\n"
"    font-size: 16px; /* Размер шрифта */\n"
"    font-family: Arial, sans-serif; /* Шрифт */\n"
"    padding: 10px 20px; /* Отступы внутри кнопки */\n"
"    border: none; /* Без рамки */\n"
"    border-radius: 5px; /* Закругление углов */\n"
"    cursor: pointer; /* Указатель при наведении */")
        self.pushButton_img.setObjectName("pushButton_img")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 330, 71, 20))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_1 = QtWidgets.QLabel(Form)
        self.label_1.setGeometry(QtCore.QRect(80, 430, 16, 16))
        self.label_1.setObjectName("label_1")
        self.pushButton_1 = QtWidgets.QPushButton(Form)
        self.pushButton_1.setGeometry(QtCore.QRect(590, 420, 111, 28))
        self.pushButton_1.setStyleSheet("background-color: #007BFF; /* Цвет фона кнопки */\n"
"    color: white; /* Цвет текста */\n"
"    font-size: 16px; /* Размер шрифта */\n"
"    font-family: Arial, sans-serif; /* Шрифт */\n"
"    padding: 5px 10px; /* Отступы внутри кнопки */\n"
"    border: none; /* Без рамки */\n"
"    border-radius: 5px; /* Закругление углов */\n"
"    cursor: pointer; /* Указатель при наведении */")
        self.pushButton_1.setObjectName("pushButton_1")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(80, 490, 16, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(590, 490, 111, 28))
        self.pushButton_2.setStyleSheet("background-color: #007BFF; /* Цвет фона кнопки */\n"
"    color: white; /* Цвет текста */\n"
"    font-size: 16px; /* Размер шрифта */\n"
"    font-family: Arial, sans-serif; /* Шрифт */\n"
"    padding: 5px 10px; /* Отступы внутри кнопки */\n"
"    border: none; /* Без рамки */\n"
"    border-radius: 5px; /* Закругление углов */\n"
"    cursor: pointer; /* Указатель при наведении */")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(610, 730, 171, 41))
        self.pushButton_7.setStyleSheet("background-color: #007BFF; /* Цвет фона кнопки */\n"
"    color: white; /* Цвет текста */\n"
"    font-size: 16px; /* Размер шрифта */\n"
"    font-family: Arial, sans-serif; /* Шрифт */\n"
"    padding: 10px 20px; /* Отступы внутри кнопки */\n"
"    border: none; /* Без рамки */\n"
"    border-radius: 5px; /* Закругление углов */\n"
"    cursor: pointer; /* Указатель при наведении */")
        self.pushButton_7.setObjectName("pushButton_7")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(110, 300, 591, 87))
        self.textEdit.setStyleSheet("background-color: #f0f0f0; /* Цвет фона */\n"
"    color: #333; /* Цвет текста */\n"
"    font-size: 16px; /* Размер шрифта */\n"
"    font-family: Arial, sans-serif; /* Шрифт */\n"
"    padding: 10px; /* Отступы внутри QLabel */\n"
"    border: 2px solid #007BFF; /* Цвет и толщина рамки */\n"
"    border-radius: 5px; /* Закругление углов */\n"
"    text-align: center; /* Выравнивание текста по центру */")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_1 = QtWidgets.QTextEdit(Form)
        self.textEdit_1.setGeometry(QtCore.QRect(110, 410, 371, 51))
        self.textEdit_1.setStyleSheet("background-color: #f0f0f0; /* Цвет фона */\n"
"    color: #333; /* Цвет текста */\n"
"    font-size: 16px; /* Размер шрифта */\n"
"    font-family: Arial, sans-serif; /* Шрифт */\n"
"    padding: 10px; /* Отступы внутри QLabel */\n"
"    border: 2px solid #007BFF; /* Цвет и толщина рамки */\n"
"    border-radius: 5px; /* Закругление углов */\n"
"    text-align: center; /* Выравнивание текста по центру */")
        self.textEdit_1.setObjectName("textEdit_1")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(110, 470, 371, 51))
        self.textEdit_2.setStyleSheet("background-color: #f0f0f0; /* Цвет фона */\n"
"    color: #333; /* Цвет текста */\n"
"    font-size: 16px; /* Размер шрифта */\n"
"    font-family: Arial, sans-serif; /* Шрифт */\n"
"    padding: 10px; /* Отступы внутри QLabel */\n"
"    border: 2px solid #007BFF; /* Цвет и толщина рамки */\n"
"    border-radius: 5px; /* Закругление углов */\n"
"    text-align: center; /* Выравнивание текста по центру */")
        self.textEdit_2.setObjectName("textEdit_2")
        self.checkBox_1 = QtWidgets.QCheckBox(Form)
        self.checkBox_1.setGeometry(QtCore.QRect(500, 420, 81, 20))
        self.checkBox_1.setObjectName("checkBox_1")
        self.checkBox_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_2.setGeometry(QtCore.QRect(500, 490, 81, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setEnabled(False)
        self.label_3.setGeometry(QtCore.QRect(80, 550, 16, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setEnabled(True)
        self.pushButton_3.setGeometry(QtCore.QRect(590, 540, 111, 28))
        self.pushButton_3.setStyleSheet("background-color: #007BFF; /* Цвет фона кнопки */\n"
"    color: white; /* Цвет текста */\n"
"    font-size: 16px; /* Размер шрифта */\n"
"    font-family: Arial, sans-serif; /* Шрифт */\n"
"    padding: 5px 10px; /* Отступы внутри кнопки */\n"
"    border: none; /* Без рамки */\n"
"    border-radius: 5px; /* Закругление углов */\n"
"    cursor: pointer; /* Указатель при наведении */")
        self.pushButton_3.setObjectName("pushButton_3")
        self.checkBox_3 = QtWidgets.QCheckBox(Form)
        self.checkBox_3.setEnabled(False)
        self.checkBox_3.setGeometry(QtCore.QRect(500, 550, 81, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.textEdit_3 = QtWidgets.QTextEdit(Form)
        self.textEdit_3.setEnabled(False)
        self.textEdit_3.setGeometry(QtCore.QRect(110, 530, 371, 51))
        self.textEdit_3.setStyleSheet("background-color: #f0f0f0; /* Цвет фона */\n"
"    color: #333; /* Цвет текста */\n"
"    font-size: 16px; /* Размер шрифта */\n"
"    font-family: Arial, sans-serif; /* Шрифт */\n"
"    padding: 10px; /* Отступы внутри QLabel */\n"
"    border: 2px solid #007BFF; /* Цвет и толщина рамки */\n"
"    border-radius: 5px; /* Закругление углов */\n"
"    text-align: center; /* Выравнивание текста по центру */")
        self.textEdit_3.setObjectName("textEdit_3")
        self.checkBox_4 = QtWidgets.QCheckBox(Form)
        self.checkBox_4.setEnabled(False)
        self.checkBox_4.setGeometry(QtCore.QRect(500, 610, 81, 20))
        self.checkBox_4.setObjectName("checkBox_4")
        self.textEdit_4 = QtWidgets.QTextEdit(Form)
        self.textEdit_4.setEnabled(False)
        self.textEdit_4.setGeometry(QtCore.QRect(110, 590, 371, 51))
        self.textEdit_4.setStyleSheet("background-color: #f0f0f0; /* Цвет фона */\n"
"    color: #333; /* Цвет текста */\n"
"    font-size: 16px; /* Размер шрифта */\n"
"    font-family: Arial, sans-serif; /* Шрифт */\n"
"    padding: 10px; /* Отступы внутри QLabel */\n"
"    border: 2px solid #007BFF; /* Цвет и толщина рамки */\n"
"    border-radius: 5px; /* Закругление углов */\n"
"    text-align: center; /* Выравнивание текста по центру */")
        self.textEdit_4.setObjectName("textEdit_4")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setEnabled(True)
        self.pushButton_4.setGeometry(QtCore.QRect(590, 600, 111, 28))
        self.pushButton_4.setStyleSheet("background-color: #007BFF; /* Цвет фона кнопки */\n"
"    color: white; /* Цвет текста */\n"
"    font-size: 16px; /* Размер шрифта */\n"
"    font-family: Arial, sans-serif; /* Шрифт */\n"
"    padding: 5px 10px; /* Отступы внутри кнопки */\n"
"    border: none; /* Без рамки */\n"
"    border-radius: 5px; /* Закругление углов */\n"
"    cursor: pointer; /* Указатель при наведении */")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setEnabled(False)
        self.label_4.setGeometry(QtCore.QRect(80, 610, 16, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setEnabled(True)
        self.pushButton_5.setGeometry(QtCore.QRect(590, 660, 111, 28))
        self.pushButton_5.setStyleSheet("background-color: #007BFF; /* Цвет фона кнопки */\n"
"    color: white; /* Цвет текста */\n"
"    font-size: 16px; /* Размер шрифта */\n"
"    font-family: Arial, sans-serif; /* Шрифт */\n"
"    padding: 5px 10px; /* Отступы внутри кнопки */\n"
"    border: none; /* Без рамки */\n"
"    border-radius: 5px; /* Закругление углов */\n"
"    cursor: pointer; /* Указатель при наведении */")
        self.pushButton_5.setObjectName("pushButton_5")
        self.checkBox_5 = QtWidgets.QCheckBox(Form)
        self.checkBox_5.setEnabled(False)
        self.checkBox_5.setGeometry(QtCore.QRect(500, 670, 81, 20))
        self.checkBox_5.setObjectName("checkBox_5")
        self.textEdit_5 = QtWidgets.QTextEdit(Form)
        self.textEdit_5.setEnabled(False)
        self.textEdit_5.setGeometry(QtCore.QRect(110, 650, 371, 51))
        self.textEdit_5.setStyleSheet("background-color: #f0f0f0; /* Цвет фона */\n"
"    color: #333; /* Цвет текста */\n"
"    font-size: 16px; /* Размер шрифта */\n"
"    font-family: Arial, sans-serif; /* Шрифт */\n"
"    padding: 10px; /* Отступы внутри QLabel */\n"
"    border: 2px solid #007BFF; /* Цвет и толщина рамки */\n"
"    border-radius: 5px; /* Закругление углов */\n"
"    text-align: center; /* Выравнивание текста по центру */")
        self.textEdit_5.setObjectName("textEdit_5")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setEnabled(False)
        self.label_5.setGeometry(QtCore.QRect(80, 660, 16, 16))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton2_1.setText(_translate("Form", "Выйти"))
        self.pushButton_save.setText(_translate("Form", "Сохранить"))
        self.pushButton_img.setText(_translate("Form", "Добавить изображение"))
        self.label.setText(_translate("Form", "Вопрос 1"))
        self.label_1.setText(_translate("Form", "1"))
        self.pushButton_1.setText(_translate("Form", "Скрыть"))
        self.label_2.setText(_translate("Form", "2"))
        self.pushButton_2.setText(_translate("Form", "Скрыть"))
        self.pushButton_7.setText(_translate("Form", "Добавить вопрос"))
        self.checkBox_1.setText(_translate("Form", "Верный"))
        self.checkBox_2.setText(_translate("Form", "Верный"))
        self.label_3.setText(_translate("Form", "3"))
        self.pushButton_3.setText(_translate("Form", "Показать"))
        self.checkBox_3.setText(_translate("Form", "Верный"))
        self.checkBox_4.setText(_translate("Form", "Верный"))
        self.pushButton_4.setText(_translate("Form", "Показать"))
        self.label_4.setText(_translate("Form", "4"))
        self.pushButton_5.setText(_translate("Form", "Показать"))
        self.checkBox_5.setText(_translate("Form", "Верный"))
        self.label_5.setText(_translate("Form", "5"))
