# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Passed.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(400, 300))
        Form.setMaximumSize(QtCore.QSize(400, 300))
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 110, 301, 51))
        self.label.setStyleSheet("background-color: #f0f0f0; /* Цвет фона */\n"
"    color: #333; /* Цвет текста */\n"
"    font-size: 16px; /* Размер шрифта */\n"
"    font-family: Arial, sans-serif; /* Шрифт */\n"
"    padding: 10px; /* Отступы внутри QLabel */\n"
"    border: 2px solid #007BFF; /* Цвет и толщина рамки */\n"
"    border-radius: 5px; /* Закругление углов */\n"
"    text-align: center; /* Выравнивание текста по центру */\n"
"")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Пройдено"))
