# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestPassing.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(800, 700))
        Form.setMaximumSize(QtCore.QSize(800, 700))
        self.pushButton2_1 = QtWidgets.QPushButton(Form)
        self.pushButton2_1.setGeometry(QtCore.QRect(20, 20, 101, 41))
        self.pushButton2_1.setStyleSheet("background-color: #007BFF; /* Цвет фона кнопки */\n"
"    color: white; /* Цвет текста */\n"
"    font-size: 16px; /* Размер шрифта */\n"
"    font-family: Arial, sans-serif; /* Шрифт */\n"
"    padding: 10px 20px; /* Отступы внутри кнопки */\n"
"    border: none; /* Без рамки */\n"
"    border-radius: 5px; /* Закругление углов */\n"
"    cursor: pointer; /* Указатель при наведении */")
        self.pushButton2_1.setObjectName("pushButton2_1")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(270, 30, 281, 211))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(130, 480, 21, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(590, 620, 181, 51))
        self.pushButton_7.setStyleSheet("background-color: #007BFF; /* Цвет фона кнопки */\n"
"    color: white; /* Цвет текста */\n"
"    font-size: 16px; /* Размер шрифта */\n"
"    font-family: Arial, sans-serif; /* Шрифт */\n"
"    padding: 10px 20px; /* Отступы внутри кнопки */\n"
"    border: none; /* Без рамки */\n"
"    border-radius: 5px; /* Закругление углов */\n"
"    cursor: pointer; /* Указатель при наведении */")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(30, 280, 91, 16))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(160, 260, 541, 81))
        self.label_9.setStyleSheet("background-color: #f0f0f0; /* Цвет фона */\n"
"    color: #333; /* Цвет текста */\n"
"    font-size: 16px; /* Размер шрифта */\n"
"    font-family: Arial, sans-serif; /* Шрифт */\n"
"    padding: 10px; /* Отступы внутри QLabel */\n"
"    border: 2px solid #007BFF; /* Цвет и толщина рамки */\n"
"    border-radius: 5px; /* Закругление углов */\n"
"    text-align: center; /* Выравнивание текста по центру */")
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_9.setObjectName("label_9")
        self.checkBox_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_2.setGeometry(QtCore.QRect(550, 430, 81, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_5 = QtWidgets.QCheckBox(Form)
        self.checkBox_5.setEnabled(True)
        self.checkBox_5.setGeometry(QtCore.QRect(550, 550, 81, 20))
        self.checkBox_5.setObjectName("checkBox_5")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(130, 520, 16, 16))
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(130, 440, 16, 16))
        self.label_2.setObjectName("label_2")
        self.textEdit_5 = QtWidgets.QTextEdit(Form)
        self.textEdit_5.setEnabled(True)
        self.textEdit_5.setGeometry(QtCore.QRect(160, 550, 371, 31))
        self.textEdit_5.setStyleSheet("background-color: #f0f0f0; /* Цвет фона */\n"
"    color: #333; /* Цвет текста */\n"
"    font-size: 16px; /* Размер шрифта */\n"
"    font-family: Arial, sans-serif; /* Шрифт */\n"
"    border: 2px solid #007BFF; /* Цвет и толщина рамки */\n"
"    border-radius: 5px; /* Закругление углов */\n"
"    text-align: center; /* Выравнивание текста по центру */")
        self.textEdit_5.setObjectName("textEdit_5")
        self.label_1 = QtWidgets.QLabel(Form)
        self.label_1.setGeometry(QtCore.QRect(130, 400, 16, 16))
        self.label_1.setObjectName("label_1")
        self.textEdit_1 = QtWidgets.QTextEdit(Form)
        self.textEdit_1.setGeometry(QtCore.QRect(160, 390, 371, 31))
        self.textEdit_1.setStyleSheet("background-color: #f0f0f0; /* Цвет фона */\n"
"    color: #333; /* Цвет текста */\n"
"    font-size: 16px; /* Размер шрифта */\n"
"    font-family: Arial, sans-serif; /* Шрифт */\n"
"    border: 2px solid #007BFF; /* Цвет и толщина рамки */\n"
"    border-radius: 5px; /* Закругление углов */\n"
"    text-align: center; /* Выравнивание текста по центру */")
        self.textEdit_1.setObjectName("textEdit_1")
        self.textEdit_3 = QtWidgets.QTextEdit(Form)
        self.textEdit_3.setEnabled(True)
        self.textEdit_3.setGeometry(QtCore.QRect(160, 470, 371, 31))
        self.textEdit_3.setStyleSheet("background-color: #f0f0f0; /* Цвет фона */\n"
"    color: #333; /* Цвет текста */\n"
"    font-size: 16px; /* Размер шрифта */\n"
"    font-family: Arial, sans-serif; /* Шрифт */\n"
"    border: 2px solid #007BFF; /* Цвет и толщина рамки */\n"
"    border-radius: 5px; /* Закругление углов */\n"
"    text-align: center; /* Выравнивание текста по центру */")
        self.textEdit_3.setObjectName("textEdit_3")
        self.checkBox_4 = QtWidgets.QCheckBox(Form)
        self.checkBox_4.setEnabled(True)
        self.checkBox_4.setGeometry(QtCore.QRect(550, 510, 81, 20))
        self.checkBox_4.setObjectName("checkBox_4")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(160, 430, 371, 31))
        self.textEdit_2.setStyleSheet("background-color: #f0f0f0; /* Цвет фона */\n"
"    color: #333; /* Цвет текста */\n"
"    font-size: 16px; /* Размер шрифта */\n"
"    font-family: Arial, sans-serif; /* Шрифт */\n"
"    border: 2px solid #007BFF; /* Цвет и толщина рамки */\n"
"    border-radius: 5px; /* Закругление углов */\n"
"    text-align: center; /* Выравнивание текста по центру */")
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_4 = QtWidgets.QTextEdit(Form)
        self.textEdit_4.setEnabled(True)
        self.textEdit_4.setGeometry(QtCore.QRect(160, 510, 371, 31))
        self.textEdit_4.setStyleSheet("background-color: #f0f0f0; /* Цвет фона */\n"
"    color: #333; /* Цвет текста */\n"
"    font-size: 16px; /* Размер шрифта */\n"
"    font-family: Arial, sans-serif; /* Шрифт */\n"
"    border: 2px solid #007BFF; /* Цвет и толщина рамки */\n"
"    border-radius: 5px; /* Закругление углов */\n"
"    text-align: center; /* Выравнивание текста по центру */")
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setEnabled(True)
        self.label_5.setGeometry(QtCore.QRect(130, 560, 16, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setEnabled(True)
        self.label_6.setGeometry(QtCore.QRect(550, 350, 231, 16))
        self.label_6.setObjectName("label_6")
        self.checkBox_1 = QtWidgets.QCheckBox(Form)
        self.checkBox_1.setGeometry(QtCore.QRect(550, 390, 81, 20))
        self.checkBox_1.setObjectName("checkBox_1")
        self.checkBox_3 = QtWidgets.QCheckBox(Form)
        self.checkBox_3.setEnabled(True)
        self.checkBox_3.setGeometry(QtCore.QRect(550, 470, 81, 20))
        self.checkBox_3.setObjectName("checkBox_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton2_1.setText(_translate("Form", "Выйти"))
        self.label_3.setText(_translate("Form", "3"))
        self.pushButton_7.setText(_translate("Form", "Следующий вопрос"))
        self.label_8.setText(_translate("Form", "Номер вопроса"))
        self.label_9.setText(_translate("Form", "Вопрос"))
        self.checkBox_2.setText(_translate("Form", "Верный"))
        self.checkBox_5.setText(_translate("Form", "Верный"))
        self.label_4.setText(_translate("Form", "4"))
        self.label_2.setText(_translate("Form", "2"))
        self.label_1.setText(_translate("Form", "1"))
        self.checkBox_4.setText(_translate("Form", "Верный"))
        self.label_5.setText(_translate("Form", "5"))
        self.label_6.setText(_translate("Form", "Выберите вариант ответа"))
        self.checkBox_1.setText(_translate("Form", "Верный"))
        self.checkBox_3.setText(_translate("Form", "Верный"))
